Repository Record-Timeline/Server, pull requests merged in 2024-07, with the labels that each got.

#26 feat: mainTimeline 제목 필드 넘겨주기
  src/main/java/com/api/RecordTimeline/domain/subTimeline/controller/SubTimelineController.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubReadResponseDTO.java
Labels: Feature, BugFix, 박현빈

#29 Rtl 35 be 사용자 팔로잉
  build.gradle
  src/main/java/com/api/RecordTimeline/domain/appLogin/service/AppLoginServiceImpl.java
  src/main/java/com/api/RecordTimeline/domain/follow/controller/FollowController.java
  src/main/java/com/api/RecordTimeline/domain/follow/domain/Follow.java
  src/main/java/com/api/RecordTimeline/domain/follow/repository/FollowRepository.java
  src/main/java/com/api/RecordTimeline/domain/follow/service/FollowService.java
  src/main/java/com/api/RecordTimeline/domain/mainPage/service/MainPageServiceImpl.java
  src/main/java/com/api/RecordTimeline/domain/search/service/SearchServiceImpl.java
  src/main/java/com/api/RecordTimeline/domain/signup/signup/service/SignupServiceImpl.java
  src/main/java/com/api/RecordTimeline/global/exception/ErrorType.java
  src/main/java/com/api/RecordTimeline/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/RecordTimeline/global/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/api/RecordTimeline/global/security/jwt/JwtProvider.java
  src/main/java/com/api/RecordTimeline/global/util/SecurityUtil.java
Labels: Feature, 박현빈

#27 Rtl 107 be 게시글 북마크
  src/main/java/com/api/RecordTimeline/domain/bookmark/service/BookmarkService.java
  src/main/java/com/api/RecordTimeline/domain/like/service/LikeService.java
Labels: Feature, 오유경
