Repository Record-Timeline/Server, pull requests merged in 2024-10, with the labels that each got.

#43 Rtl 125 be 서브타임라인 댓글 대댓글
  src/main/java/com/api/RecordTimeline/domain/comment/controller/CommentController.java
  src/main/java/com/api/RecordTimeline/domain/comment/domain/Comment.java
  src/main/java/com/api/RecordTimeline/domain/comment/dto/request/CommentCreateRequestDTO.java
  src/main/java/com/api/RecordTimeline/domain/comment/dto/request/CommentUpdateRequestDTO.java
  src/main/java/com/api/RecordTimeline/domain/comment/dto/response/CommentDeleteResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/comment/dto/response/CommentUpdateResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/comment/repository/CommentRepository.java
  src/main/java/com/api/RecordTimeline/domain/comment/service/CommentService.java
  src/main/java/com/api/RecordTimeline/domain/reply/controller/ReplyController.java
  src/main/java/com/api/RecordTimeline/domain/reply/domain/Reply.java
  src/main/java/com/api/RecordTimeline/domain/reply/dto/request/ReplyCreateRequestDTO.java
  src/main/java/com/api/RecordTimeline/domain/reply/dto/request/ReplyUpdateRequestDTO.java
  src/main/java/com/api/RecordTimeline/domain/reply/dto/response/ReplyDeleteResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/reply/dto/response/ReplyResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/reply/dto/response/ReplyUpdateResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/reply/repository/ReplyRepository.java
  src/main/java/com/api/RecordTimeline/domain/reply/service/ReplyService.java
Labels: Feature, 오유경

#46 Rtl 129 be 북마크/좋아요 해제 에러 수정
  src/main/java/com/api/RecordTimeline/domain/bookmark/domain/Bookmark.java
  src/main/java/com/api/RecordTimeline/domain/bookmark/service/BookmarkService.java
  src/main/java/com/api/RecordTimeline/domain/like/domain/UserLike.java
  src/main/java/com/api/RecordTimeline/domain/like/service/LikeService.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/domain/SubTimeline.java
Labels: BugFix, 오유경

#47 44 알림 기능
  build.gradle
  src/main/java/com/api/RecordTimeline/RecordTimelineApplication.java
  src/main/java/com/api/RecordTimeline/domain/follow/service/FollowService.java
  src/main/java/com/api/RecordTimeline/domain/like/service/LikeService.java
  src/main/java/com/api/RecordTimeline/domain/mainPage/dto/response/MainPageMemberDto.java
  src/main/java/com/api/RecordTimeline/domain/mainPage/dto/response/MainPageSubTimelineDto.java
  src/main/java/com/api/RecordTimeline/domain/mainPage/dto/response/MainTimelineDto.java
  src/main/java/com/api/RecordTimeline/domain/notification/controller/NotificationController.java
  src/main/java/com/api/RecordTimeline/domain/notification/domain/Notification.java
  src/main/java/com/api/RecordTimeline/domain/notification/domain/NotificationType.java
  src/main/java/com/api/RecordTimeline/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/api/RecordTimeline/domain/notification/repository/NotificationRepository.java
  src/main/java/com/api/RecordTimeline/domain/notification/service/NotificationCleanupService.java
  src/main/java/com/api/RecordTimeline/domain/notification/service/NotificationService.java
  src/main/java/com/api/RecordTimeline/global/config/SecurityConfig.java
  src/main/java/com/api/RecordTimeline/global/config/WebSoketConfig.java
  src/main/resources/static/notification.html
Labels: Feature, 박현빈
