Repository Record-Timeline/Server, pull requests merged in 2024-08, with the labels that each got.

#30 Rtl 109 be 아이디 비밀번호 찾기
  src/main/java/com/api/RecordTimeline/domain/findInfo/password/controller/PasswordResetController.java
  src/main/java/com/api/RecordTimeline/domain/findInfo/password/dto/request/PasswordResetDto.java
  src/main/java/com/api/RecordTimeline/domain/findInfo/password/dto/request/PasswordResetRequestDto.java
  src/main/java/com/api/RecordTimeline/domain/findInfo/password/service/PasswordResetService.java
  src/main/java/com/api/RecordTimeline/domain/signup/email/domain/EmailCertification.java
  src/main/java/com/api/RecordTimeline/domain/signup/email/dto/request/CheckCertificationRequestDto.java
  src/main/java/com/api/RecordTimeline/domain/signup/email/dto/request/EmailCertificationRequestDto.java
  src/main/java/com/api/RecordTimeline/domain/signup/email/repository/EmailCertificationRepository.java
  src/main/java/com/api/RecordTimeline/domain/signup/email/service/EmailServiceImpl.java
  src/main/java/com/api/RecordTimeline/domain/signup/signup/service/SignupServiceImpl.java
  src/main/java/com/api/RecordTimeline/global/exception/ErrorType.java
Labels: Feature, 박현빈

#31 Rtl 115 be 기능 수정
  src/main/java/com/api/RecordTimeline/domain/career/domain/Career.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/CareerDetail.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/Certificate.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/Education.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/ForeignLanguage.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/Proficiency.java
  src/main/java/com/api/RecordTimeline/domain/career/repository/CareerDetailRepository.java
  src/main/java/com/api/RecordTimeline/domain/career/repository/CareerRepository.java
  src/main/java/com/api/RecordTimeline/domain/career/repository/CertificateRepository.java
  src/main/java/com/api/RecordTimeline/domain/career/repository/EducationRepository.java
  src/main/java/com/api/RecordTimeline/domain/career/repository/ForeignLanguageRepository.java
  src/main/java/com/api/RecordTimeline/domain/findInfo/password/controller/PasswordResetController.java
  src/main/java/com/api/RecordTimeline/domain/follow/controller/FollowController.java
  src/main/java/com/api/RecordTimeline/domain/follow/repository/FollowRepository.java
  src/main/java/com/api/RecordTimeline/domain/follow/service/FollowService.java
  src/main/java/com/api/RecordTimeline/domain/member/dto/response/MemberInfoResponseDto.java
  src/main/java/com/api/RecordTimeline/domain/member/service/MemberServiceImpl.java
  src/main/java/com/api/RecordTimeline/domain/search/service/SearchServiceImpl.java
  src/main/java/com/api/RecordTimeline/global/config/SecurityConfig.java
Labels: Feature, BugFix, 박현빈

#32 Rtl 116 be 기능 수정 1
  src/main/java/com/api/RecordTimeline/domain/bookmark/dto/response/BookmarkedPostResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/bookmark/service/BookmarkService.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/repository/MainTimelineRepository.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/controller/SubTimelineController.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/request/SubTimelineCreateRequest.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubReadResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubTimelineWithLikeBookmarkDTO.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/service/SubTimelineService.java
  src/main/java/com/api/RecordTimeline/global/exception/ErrorType.java
Labels: Feature, 오유경

#33 Rtl 41 be 경력사항 crud
  src/main/java/com/api/RecordTimeline/domain/career/controller/CareerController.java
  src/main/java/com/api/RecordTimeline/domain/career/controller/CareerDetailController.java
  src/main/java/com/api/RecordTimeline/domain/career/controller/CertificateController.java
  src/main/java/com/api/RecordTimeline/domain/career/controller/EducationController.java
  src/main/java/com/api/RecordTimeline/domain/career/controller/ForeignLanguageController.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/Career.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/CareerDetail.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/Certificate.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/Education.java
  src/main/java/com/api/RecordTimeline/domain/career/domain/ForeignLanguage.java
  src/main/java/com/api/RecordTimeline/domain/career/dto/CareerDetailDto.java
  src/main/java/com/api/RecordTimeline/domain/career/dto/CareerDto.java
  src/main/java/com/api/RecordTimeline/domain/career/dto/CertificateDto.java
  src/main/java/com/api/RecordTimeline/domain/career/dto/EducationDto.java
  src/main/java/com/api/RecordTimeline/domain/career/dto/ForeignLanguageDto.java
  src/main/java/com/api/RecordTimeline/domain/career/repository/CareerDetailRepository.java
  src/main/java/com/api/RecordTimeline/domain/career/service/CareerDetailService.java
  src/main/java/com/api/RecordTimeline/domain/career/service/CareerService.java
  src/main/java/com/api/RecordTimeline/domain/career/service/CertificateService.java
  src/main/java/com/api/RecordTimeline/domain/career/service/EducationService.java
  src/main/java/com/api/RecordTimeline/domain/career/service/ForeignLanguageService.java
  src/main/java/com/api/RecordTimeline/domain/member/domain/Member.java
  src/main/java/com/api/RecordTimeline/domain/member/service/MemberServiceImpl.java
  src/main/java/com/api/RecordTimeline/global/exception/ErrorType.java
Labels: Feature, 박현빈

#34 Rtl 47 be 메인 타임라인 공개여부 설정
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/controller/MainTimelineController.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/domain/MainTimeline.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/dto/response/PrivacyUpdateResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/service/MainTimelineService.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/service/SubTimelineService.java
  src/main/java/com/api/RecordTimeline/global/exception/ApiException.java
  src/main/java/com/api/RecordTimeline/global/exception/ErrorType.java
Labels: Feature, 오유경

#35 Rtl 48 be 서브 타임라인 공개여부 설정
  src/main/java/com/api/RecordTimeline/domain/subTimeline/controller/SubTimelineController.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/domain/SubTimeline.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubMyTimelineResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubPrivacyUpdateResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubReadResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/repository/SubTimelineRepository.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/service/SubTimelineService.java
Labels: Feature, 오유경

#36 feat: 진행중/완료 isDone 필드 추가 및 API 생성
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/controller/MainTimelineController.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/domain/MainTimeline.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/dto/response/ReadResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/dto/response/UpdateStatusResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/service/MainTimelineService.java
Labels: Feature, 오유경

#37 RTL 118 be 서브 타임라인 공개여부 설정
  src/main/java/com/api/RecordTimeline/domain/subTimeline/controller/SubTimelineController.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/domain/SubTimeline.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubMyTimelineResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubReadResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/dto/response/SubUpdateStatusResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/service/SubTimelineService.java
Labels: Feature, 오유경

#38 Rtl 121 be 타임라인 진행중 상태 토글로 변경
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/controller/MainTimelineController.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/dto/response/MainUpdateStatusResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/dto/response/UpdateStatusResponseDTO.java
  src/main/java/com/api/RecordTimeline/domain/mainTimeline/service/MainTimelineService.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/controller/SubTimelineController.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/service/SubTimelineService.java
Labels: Feature, 오유경

#39 Rtl 122 be 서브타임라인 delete 수정
  src/main/java/com/api/RecordTimeline/domain/bookmark/domain/Bookmark.java
  src/main/java/com/api/RecordTimeline/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/api/RecordTimeline/domain/like/domain/UserLike.java
  src/main/java/com/api/RecordTimeline/domain/like/repository/LikeRepository.java
  src/main/java/com/api/RecordTimeline/domain/subTimeline/service/SubTimelineService.java
Labels: Feature, 오유경
